### ISSUE TITLE
App crash when i try open Message Center.

### ISSUE THREAD

**Issue by RamilGabdrakhmanov** [apptentive/apptentive-android#134]
I use support libraries 25.3.1 and multidex:1.0.1

And try do this:
```
if (Apptentive.canShowMessageCenter()) {
        Apptentive.showMessageCenter(getActivity());
      }
```

Result: App crashed on android < 21

```
FATAL EXCEPTION: main
Process: com.jrummy.font.installer.staging, PID: 21901
android.view.InflateException: Binary XML file line #27: Error inflating class ImageButton
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at com.apptentive.android.sdk.module.messagecenter.view.MessageCenterRecyclerViewAdapter.onCreateViewHolder(MessageCenterRecyclerViewAdapter.java:85)
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
at android.view.View.layout(View.java:15132)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
at android.view.View.layout(View.java:15132)
at android.view.ViewGroup.layout(ViewGroup.java:4662)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at and
```

**Comment by skykelsey** [comment]
Thank you Ramil. We'll take look.

**Comment by skykelsey** [comment]
Hi @RamilGabdrakhmanov, do you happen to have a complete stacktrace, or just more logs in general? Can you please send them to sky@apptentive.com? The stack trace you posted is clipped and missing the actual cause, since layout inflation errors are generally nested exceptions.

**Comment by skykelsey** [comment]
Hi @RamilGabdrakhmanov. I wanted to see if you were able to send complete logs of the stacktrace. I'm not going to be able to diagnose the issue unless I see the root cause of the inflation error. I will say that in the past, this kind of thing is cause by not using the correct version of the support libraries. We require a minimum of 24.2.1.

**Comment by skykelsey** [comment]
This is most likely because you are trying to use an old version of the support libraries. If you see this, and can answer my questions, I'll reopen.
