### ISSUE TITLE
StrictMode policy violations when initializing Android SDK

### ISSUE THREAD

**Issue by gmbett** [apptentive/apptentive-android#159]
Hi,

When the Android SDK is initialized by
```java
Apptentive.register(context, key, signature);
```

A lot of issues are detected by strict mode (disk read on UI thread):

> StrictMode: StrictMode policy violation; ~duration=26 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:541)
        at android.app.ContextImpl.getCacheDir(ContextImpl.java:613)
        at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:283)
        at com.apptentive.android.sdk.ApptentiveLog.getLogsDirectory(ApptentiveLog.java:135)
        at com.apptentive.android.sdk.ApptentiveLog.initializeLogWriter(ApptentiveLog.java:36)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:216)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

>  StrictMode policy violation; ~duration=18 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:541)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:497)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:656)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:374)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:171)
        at com.apptentive.android.sdk.ApptentiveInternal.<init>(ApptentiveInternal.java:164)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:229)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

>  StrictMode policy violation; ~duration=17 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:203)
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:224)
        at com.apptentive.android.sdk.ApptentiveInternal.getEndpointBase(ApptentiveInternal.java:914)
        at com.apptentive.android.sdk.ApptentiveInternal.<init>(ApptentiveInternal.java:165)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:229)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

> StrictMode policy violation; ~duration=16 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:541)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:562)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:253)
        at com.apptentive.android.sdk.util.Util.getInternalDir(Util.java:1100)
        at com.apptentive.android.sdk.ApptentiveInternal.<init>(ApptentiveInternal.java:167)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:229)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

>  StrictMode policy violation; ~duration=16 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at com.apptentive.android.sdk.util.Util.getInternalDir(Util.java:1102)
        at com.apptentive.android.sdk.ApptentiveInternal.<init>(ApptentiveInternal.java:167)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:229)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

> StrictMode policy violation; ~duration=13 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1293)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:249)
        at java.io.File.exists(File.java:780)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:541)
        at android.app.ContextImpl.getFilesDir(ContextImpl.java:562)
        at android.content.ContextWrapper.getFilesDir(ContextWrapper.java:253)
        at com.apptentive.android.sdk.storage.ApptentiveDatabaseHelper.<init>(ApptentiveDatabaseHelper.java:229)
        at com.apptentive.android.sdk.storage.ApptentiveTaskManager.<init>(ApptentiveTaskManager.java:68)
        at com.apptentive.android.sdk.ApptentiveInternal.<init>(ApptentiveInternal.java:170)
        at com.apptentive.android.sdk.ApptentiveInternal.createInstance(ApptentiveInternal.java:229)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:124)
        at com.apptentive.android.sdk.Apptentive.register(Apptentive.java:106)

Is there any plan to fix these issues ? (I'm using the latest version)

**Comment by weeeBox** [comment]
Hi @gmbett,

Thanks for finding these issues. We'll fix them in a future release. Stay tuned!

-Alex

**Comment by alexandru-calinoiu** [comment]
@weeeBox any updates on this issue?

**Comment by weeeBox** [comment]
Hi @gmbett,

Sorry for the delay. We're getting this item triaged and hopefully include the fix into the next release.

**Comment by alexandru-calinoiu** [comment]
@weeeBox planning a release soon?

**Comment by weeeBox** [comment]
We're planning to incorporate it in the upcoming release (some time after Google I/O)
