### ISSUE TITLE
App crashes on :- Provider is not registered: interface apptentive.com.android.feedback.dependencyprovider.a

### ISSUE THREAD

**Issue by sabuthm** [apptentive/apptentive-android#241]
Hello Apptentive team,
We are facing an app crash with the following crash log, please let us know the fix for this or if you need any more information

## Device

Brand:Google
Model:Pixel 3a

## Operating System
Version:Android 11

## Apptentive Version : 6.0.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.app/apptentive.com.android.feedback.messagecenter.view.MessageCenterActivity}: java.lang.IllegalArgumentException: Provider is not registered: interface apptentive.com.android.feedback.dependencyprovider.a
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loop(Looper.java:223)
    android.app.ActivityThread.main(ActivityThread.java:7664)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: Provider is not registered: interface apptentive.com.android.feedback.dependencyprovider.a
    apptentive.com.android.core.DependencyProvider.of(DependencyProvider.java:25)
    apptentive.com.android.feedback.dependencyprovider.MessageCenterViewModelUtilsKt.createMessageCenterViewModel$default(MessageCenterViewModelUtils.kt:12)
    apptentive.com.android.feedback.messagecenter.view.BaseMessageCenterActivity$viewModel$2$1.invoke(BaseMessageCenterActivity.kt:28)
    apptentive.com.android.feedback.messagecenter.view.BaseMessageCenterActivity$viewModel$2$1.invoke(BaseMessageCenterActivity.kt:28)
    apptentive.com.android.ui.ViewModelFactory.create(ViewModelFactory.kt:12)
    androidx.lifecycle.ViewModelProvider$Factory$-CC.b(ViewModelProvider.kt:10)
    apptentive.com.android.ui.ViewModelFactory.create(ViewModelFactory.kt:0)
    androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
    androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
    androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
    androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
    apptentive.com.android.feedback.messagecenter.view.BaseMessageCenterActivity.getViewModel(BaseMessageCenterActivity.kt:27)
    apptentive.com.android.feedback.messagecenter.view.MessageCenterActivity.onCreate(MessageCenterActivity.kt:74)
    android.app.Activity.performCreate(Activity.java:7994)
    android.app.Activity.performCreate(Activity.java:7978)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loop(Looper.java:223)
    android.app.ActivityThread.main(ActivityThread.java:7664)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by CaseyApptentive** [comment]
Sorry for the crash @sabuthm. We're looking into this.

**Comment by CaseyApptentive** [comment]
@sabuthm can you try using [6.0.2](https://github.com/apptentive/apptentive-kit-android/releases/tag/v.6.0.2) and see if it's still causing a crash? This looks like a bug that we fixed recently. 

Let us know if you're still having any trouble. Thanks!

**Comment by CaseyApptentive** [comment]
@sabuthm did that work for you? Let me know if this was resolved. Thanks!

**Comment by sabuthm** [comment]
@CaseyApptentive we were monitoring the issue after updating the version to 6.0.2. we were able to capture the same crash again. 
Following is the crash log..
~~~
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.magnolia.android.app/apptentive.com.android.feedback.messagecenter.view.ProfileActivity}: java.lang.IllegalArgumentException: Provider is not registered: interface apptentive.com.android.feedback.message.e
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
~~~

~~~
Caused by java.lang.IllegalArgumentException: Provider is not registered: interface apptentive.com.android.feedback.message.e
       at apptentive.com.android.core.DependencyProvider.of(DependencyProvider.java:25)
       at apptentive.com.android.feedback.messagecenter.viewmodel.ProfileViewModel.<init>(ProfileViewModel.kt:22)
       at apptentive.com.android.feedback.messagecenter.view.BaseProfileActivity$viewModel$2$1.invoke(BaseProfileActivity.kt:28)
       at apptentive.com.android.feedback.messagecenter.view.BaseProfileActivity$viewModel$2$1.invoke(BaseProfileActivity.kt:28)
       at apptentive.com.android.ui.ViewModelFactory.create(ViewModelFactory.kt:12)
       at androidx.lifecycle.ViewModelProvider$Factory$-CC.b(ViewModelProvider.kt:10)
       at apptentive.com.android.ui.ViewModelFactory.create(ViewModelFactory.kt)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
       at apptentive.com.android.feedback.messagecenter.view.BaseProfileActivity.getViewModel(BaseProfileActivity.kt:27)
       at apptentive.com.android.feedback.messagecenter.view.ProfileActivity.onCreate(ProfileActivity.kt:27)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
~~~
following are the device info
~~~
Brand:Google
Model:Pixel 3a
Orientation: Portrait
RAM free: 1.68 GB
Disk free: 46.7 GB
Version:Android 11


Brand:Google
Model:Pixel 4a
Orientation: Portrait
RAM free: 3.36 GB
Disk free: 105.77 GB
Version:Android 11
~~~

**Comment by prakash-robosoft** [comment]
@CaseyApptentive any idea to fix this crash, please?
